redis_metrics:
    build: .
    links:
        - redis_1
        - redis_2
        - statsd

redis_1:
  image: redis
  ports:
    - "6379"

redis_2:
  image: redis
  ports:
    - "6379"

statsd:
  image: daime/docker-statsd-console
  ports:
    - "8125"
    - "8126"
